export const links = {
  home: 'https://leadster.com.br/',
  ferramenta: 'https://leadster.com.br/leads-qualificados-com-anuncios/',
  preco: 'https://leadster.com.br/preco/',
  contato: 'https://leadster.com.br/contato/',
  b2b: 'https://leadster.com.br/geracao-de-leads/b2b/',
  software: 'https://leadster.com.br/geracao-de-leads/software/',
  imobiliaria: 'https://leadster.com.br/geracao-de-leads/imobiliaria/',
  cases: 'https://leadster.com.br/estudo-de-caso/',
  blog: 'https://leadster.com.br/blog/',
  parceria: 'https://leadster.com.br/agencias-parceiras/programa/',
  guia: 'https://leadster.com.br/marketing-conversacional/',
  gratuitos: 'https://leadster.com.br/materiais/',
  email: 'mailto:contato@leadster.com.br',
  telefone: 'https://api.whatsapp.com/send?phone=5542988289851',
  demonstracao: 'https://leadster.com.br/chatbot-leadster/?utm_source=clientes&utm_medium=referral&utm_campaign=leadster.com.br',
  termosDeUso: 'https://leadster.com.br/termos_de_uso/',
  privacidade: 'https://leadster.com.br/privacidade/',
  linkedin: 'https://www.linkedin.com/company/leadster-platform/',
  facebook: 'https://web.facebook.com/leadsterplatform',
  instagram: 'https://www.instagram.com/leadster.com.br/',
}